/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export interface Settings {
  dbName?: string;
  host?: string;
  port?: number;
  username?: string;
  password?: string;
  queryString?: string;
  driverOptions?: {
    useUnifiedTopology?: boolean;
    [k: string]: unknown;
  };
  [k: string]: unknown;
}
